import tkinter
from tkinter import *
def Home():
    New_win=Tk()
    New_win.title("Notice")  
    New_win.pack()  
window = Tk()
window.title("Library Manager")
window.geometry('1400x1400')
top_label=Label(window,text="Library Manager",fg='green',font='sans-serif 50 bold',bg='red')
top_label.pack()
Name_of_Student=Label(window,text="Student's name",font='sans-serif 20 italic',fg="blue",bg="yellow")
Name_of_Student.pack()
Name_of_Student_entry=Entry(window,width="50",bg="lightgrey").pack()
Name_of_books=Label(window,text="Book's name borrowed",fg="blue",bg="yellow",font='sans-serif 20 italic')
Name_of_books.pack()
Name_of_books_entry=Entry(window,width="50",bg="lightgrey").pack()
Class=Label(window,text="Student's class",font='sans-serif 20 italic',fg="blue",bg="yellow")
Class.pack()
Class_entry=Entry(window,width="50",bg="lightgrey").pack()
Section_stream=Label(window,text="Section or Subject Stream",font='sans-serif 20 italic',fg="blue",bg="yellow")
Section_stream.pack()
Section_stream_entry=Entry(window,width="50",bg="lightgrey").pack()
Admin_no=Label(window,text="Student's Admission number",font='sans-serif 20 italic',fg="blue",bg="yellow")
Admin_no.pack()
Admin_no_entry=Entry(window,width="50",bg="lightgrey").pack()
Issued_date=Label(window,text="Issued Date for book",font='sans-serif 20 italic',fg="blue",bg="yellow")
Issued_date.pack()
Issued_date_entry=Entry(window,width="50",bg="lightgrey").pack()
Issued_till_date=Label(window,text="Issued untill date",font='sans-serif 20 italic',fg="blue",bg="yellow")
Issued_till_date.pack()
Issued_till_date_entry=Entry(window,width="50",bg="lightgrey").pack()
Save_file=Button(window,text="Add this details",activebackground="red",activeforeground="green",width="20",fg="red",bg="green",font="segoe-script 15 italic",bd="4")
Save_file.place(x=550,y=600)
Save_file.config(command="Home()")
window.mainloop()